config/routes.rb
Rails.application.routes.draw do
  get 'users/new'
  get 'users/create'
  root to: 'rooms#index'
  resources :rooms

  get"signup",to: "users#new"
  post"signup",to: "users#create"

  get"login",to: "sessions#new"
  post"login",to: "sessions#create"

  delete "logout", to: "sessions#destroy"
end

app/views/layouts/_footer.html.erb
<footer>
  <span>Philippine Ruby Users Group</span>
</footer>

app/views/layouts/_header.html.erb
<header class="bg-gray-500">
  <div>
    <%= image_tag "PhRUG.jpg", class: "logo" %>
  </div>
  <h1>
    <%=  t("app_name") %>
  </h1>
  <span>
    <%=  t("app_subtitle") %>
  </span>
</header>

app/views/layouts/_nav.html.erb
<nav>
  <div class="container navbar borderYtoX">
    <%= link_to(t("app_name"), root_path) %>
    <% if Current.user %>
        Welcome, <%= Current.user.name %>!
      <%= link_to t(".logout"), logout_path, data: {turbo_method: :delete} %>
    <% else %>
      <%= link_to "Sign Up", signup_path %>
      <%= link_to t(".sessions.new.title"), login_path %>
    <% end %>
  </div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= title %></title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
    <%= yield :head %>
    <link rel="icon" type="image/png" href="favicon.png" sizes="32x32" %>
  </head>

  <body>
    <%= render "layouts/header" %>
    <%= render "layouts/nav" %>
    <%= render "application/flashes" %>
    <main>
      <%= yield %>
    </main>
    <%= render "layouts/footer" %>
  </body>
</html>